Lang.prototype.pack.jp = {
	"token": {
		"Airtest Report": "テストレポート",
		"script running report": "実行結果",
        "Contact Us": "連絡先",
		"I am sorry, this log file is empty!": "実行ログファイルが見つかりませんでした",
		"Report": "テストレポート",
		"Test Case": "テストケース",
		"Steps: ": "ステップ数：",
		"Time: ": "時間：",
		"Quick view": "クイックビュー",
		"[Passed]": "[成功]",
		"[Failed]": "[失敗]",
		'[Terminated]': "[実行異常]",
		"Executors": "担当者",
		"Author:": "設計者：",
		"Author: Anonymous": "設計者：匿名",
		"Device:": "デバイス：",
		"Connect:": '接続：',
		"Accomplished:": "実施済：",
		"Rate:": '成功率：',
		"Succeed:": '実行成功：',
		'Failed:':'実行失敗:',
		"No of device:": 'デバイス番号：',
		"No of script:": "スクリプト番号：",
		"Type:": 'タイプ：',
		"Assert: Test Steps Summary": "判別：テストサマリー",
		"Test step": "テストステップ",
		"Steps:": "ステップ数：",
		"Expected result:": "期待値：",
		"order":"番号順",
		"duration": "種別順",
		"status": "結果順",
		"Jump to wrong step": "失敗項目へ",
		"Filter by:": "フィルタ：",
		"All": "全部",
		"Failed": "失敗",
		"Success": "成功",
		"Assert": "判別",
		"show all steps": "全ステップ表示",
		"show success steps only": "成功のみ",
		"show failed steps only": "失敗のみ",
		"show steps with assertion only": "判別",
		"No record information found.": "レコードが存在しない",
		"Target object": "対象",
		"Runtime screenshot": "スクリーンショット",
		"Confidence:": "マッチング率：",
		"Execution finished successfully": "実施成功",
		"Execution failed": "実施失敗",
		"Steps navigation": "ナビゲーション",
		"Related information": "インフォメーション",
		"Touch": "OCRタッチ",
		"Swipe": "スワイプ",
		"Wait": "動作待ち",
		"Exists": "OCR判別：存在",
		"Text": "テキスト入力",
		"Keyevent": "デバイス操作キー",
		"Sleep": "待機",
		"Server call": "サーバーコール",
		"Assert exists": "判別：存在",
		"Assert not exists": "判別：存在なし",
		"Snapshot": "画面表示・操作",
		"Assert equal": "判別：一致",
		"Assert not equal": "判別：不一致",
		"start_app": "アプリ起動",
		"stop_app": "アプリ終了",
		"Assert:": "判別：",
		"Title": "タイトル",
		"Description:": "概要：",
		"Time:": "実施時間：",
		"Behavior:": "動作：",
		"Duration:": "実行時間：",
		"Status:": "結果：",
		"Total": "合計",
		"Warning: No steps": "対象ステップはありません",
		"© 1997 - 2019 NetEase, Inc. All Rights Reserved.": "© 1997 - 2019 ネットイース"
	}
};